name: CI/CD Lambda Hola Mundo

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: hola-mundo

jobs:
  terraform-infra:
    runs-on: ubuntu-latest
    outputs:
      ecr_url: ${{ steps.set-ecr.outputs.ecr_url }}
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve -var="create_lambda=false"

      - name: Set ECR Output
        id: set-ecr
        run: |
          URL=$(terraform output -raw ecr_repository_url)
          echo "ecr_url=$URL" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: terraform-infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        run: |
          ECR_URL=${{ needs.terraform-infra.outputs.ecr_url }}
          docker build -t $ECR_URL:latest .
          docker push $ECR_URL:latest

  deploy-lambda:
    runs-on: ubuntu-latest
    needs: [terraform-infra, build-and-push]
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init & Apply (Crear Lambda)
        run: |
          terraform init
          terraform apply -auto-approve -var="create_lambda=true"